Revert "KVM: arm64: Fix symbol dependency in __hyp_call_panic_nvhe"
* fixes build error with GCC 4.9

lineage17/kernel/brcm/rpi/arch/arm64/kvm/hyp/switch.c: In function 'hyp_panic':
lineage17/kernel/brcm/rpi/arch/arm64/kvm/hyp/switch.c:761:2: error: impossible constraint in 'asm'
  asm volatile("ldr %0, =%1" : "=r" (str_va) : "S" (__hyp_panic_string));
  ^

This reverts commit 653ae33b030ba18bff399f3500c405ede2c3db63.